env:
  es2021: true
  node: true
extends:
  - google
  - eslint:recommended
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 12
  sourceType: module
plugins:
  - '@typescript-eslint'
rules: {
  max-len: [2, {"code": 120, "tabWidth": 2, "ignoreUrls": true}]
}
