apiVersion: apps/v1

kind: Deployment
metadata:
  name: user-svc
  labels:
    app: user-svc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-svc
  template:
    metadata:
      labels:
        app: user-svc
    spec:
      containers:
      - name: udagram-image-user
        image: fgaviria/udagram-image-user:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 9898
        resources:
          requests: { memory: 10Mi, cpu: "0.1" }
          limits: { memory: 256Mi, cpu: "0.5" }
        env:
          - name: DB_USERNAME
            value: <YOUR_DB_USERNAME>
          - name: DB_PASSWORD
            value: <YOUR_DB_PASSWORD>
          - name: DB_NAME
            value: <YOUR_DB_NAME>
          - name: DB_HOST
            value: <YOUR_DB_HOST>
          - name: DB_DIALECT
            value: postgres
          - name: CLIENTS_URLS
            value: "*"
          - name: JWT_SECRET
            value: <YOUR_JWT_SECRET>
          - name: PORT
            value: "9898"
          - name: FORCE_DEPLOY
            value: "1"
        livenessProbe:
          httpGet:
            path: "/"
            port: 9898
          initialDelaySeconds: 3
          periodSeconds: 60
        readinessProbe:
          httpGet:
            path: "/"
            port: 9898
          initialDelaySeconds: 3
