apiVersion: v1

kind: Service
metadata:
  name: user-svc
  labels:
    run: user-svc
spec:
  selector:
    app: user-svc
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 9898
  type: ClusterIP
